export default {
  tabs: { dashboard: 'डैशबोर्ड', log: 'रिकॉर्ड', trends: 'रुझान', dosing: 'सुधार', settings: 'सेटिंग्स' },
  params: { temperature: 'तापमान', salinity: 'लवणता', ph: 'pH', alkalinity: 'क्षारीयता', calcium: 'कैल्शियम', magnesium: 'मैग्नीशियम', nitrate: 'नाइट्रेट', phosphate: 'फॉस्फेट', ammonia: 'अमोनिया', nitrite: 'नाइट्राइट', potassium: 'पोटैशियम', strontium: 'स्ट्रोंटियम', iodine: 'आयोडीन', boron: 'बोरॉन', silicate: 'सिलिकेट' },
  dashboard: { waterChemistry: 'जल रसायन', nutrients: 'पोषक तत्व', ratioNO3PO4: 'NO3:PO4 अनुपात', ionicBalance: 'आयनिक संतुलन', noData: 'कोई डेटा नहीं' },
  log: { subtitle: 'रिकॉर्ड करने के लिए पैरामीटर टैप करें', cancel: 'रद्द करें', save: 'सहेजें', saving: 'सहेज रहे हैं...', step: 'स्टेप' },
  timers: { title: 'Salifert टाइमर', shake: '30 सेकंड हिलाएं', wait: '3 मिनट प्रतीक्षा करें', start: 'शुरू', cancel: 'रद्द करें', done: 'पूर्ण' },
  trends: { consumptionRate: 'खपत दर', consumptionHigh: 'उच्च खपत — मूंगे सक्रिय रूप से बढ़ रहे हैं', consumptionNormal: 'सामान्य — स्थिर अवशोषण', consumptionStable: 'स्थिर — कोई शुद्ध परिवर्तन नहीं', consumptionRising: 'बढ़ रहा है — डोसिंग जांचें', history: 'इतिहास', noReadings: 'इस अवधि में कोई रीडिंग नहीं', deleteTitle: 'रीडिंग हटाएं', deleteMessage: '%{date} का %{value} %{unit}?', deleteConfirm: 'हटाएं' },
  chart: { noReadings: 'कोई रीडिंग नहीं', noReadingsHint: 'रुझान देखने के लिए अपनी पहली %{param} रीडिंग रिकॉर्ड करें', current: 'वर्तमान', min: 'न्यूनतम', max: 'अधिकतम', avg: 'औसत' },
  settings: { parameters: 'पैरामीटर', thresholds: 'अलर्ट सीमाएं', data: 'डेटा', dosingLog: 'डोसिंग लॉग', exportCsv: 'CSV निर्यात', noDataExport: 'कोई डेटा नहीं', noDataExportMsg: 'निर्यात के लिए कोई रीडिंग नहीं।', save: 'सहेजें', importCsv: 'CSV बैकअप आयात करें', importSuccess: 'आयात पूर्ण', importSuccessMsg: '%{count} रीडिंग आयात की गईं।', importError: 'आयात विफल', warnLow: 'चेतावनी निम्न', warnHigh: 'चेतावनी उच्च', critLow: 'गंभीर निम्न', critHigh: 'गंभीर उच्च' },
  dosing: { title: 'डोसिंग लॉग', add: 'डोज़ जोड़ें', empty: 'कोई डोज़ रिकॉर्ड नहीं', emptyHint: 'पैरामीटर परिवर्तनों से सहसंबंध के लिए अपनी डोज़ रिकॉर्ड करें', product: 'उत्पाद', productPlaceholder: 'या उत्पाद का नाम टाइप करें...', amount: 'मात्रा', notes: 'नोट्स', notesPlaceholder: 'वैकल्पिक...', cancel: 'रद्द करें', save: 'सहेजें', products: { kalkwasser: 'Kalkwasser', allForReef: 'All-for-Reef', caBalling: 'Ca (बॉलिंग)', alkBalling: 'Alk (बॉलिंग)', mgSupplement: 'Mg सप्लीमेंट', aminoAcids: 'अमीनो एसिड', coralFood: 'कोरल फूड' } },
  ratios: { po4Undetectable: 'उच्च NO3 के साथ PO4 अनडिटेक्टेबल — सायनो/डायनो का खतरा', no3Undetectable: 'उच्च PO4 के साथ NO3 अनडिटेक्टेबल — पोषक असंतुलन', insufficientData: 'अपर्याप्त डेटा', ratioLow: 'NO3:PO4 अनुपात कम (%{ratio}:1) — फॉस्फेट अधिक', ratioHigh: 'NO3:PO4 अनुपात उच्च (%{ratio}:1) — नाइट्रेट अधिक', ratioOk: 'NO3:PO4 अनुपात %{ratio}:1', mgLow: 'Ca की तुलना में Mg बहुत कम — पहले Mg बढ़ाएं', mgHigh: 'Ca की तुलना में Mg बहुत अधिक', mgInstability: 'कम Mg Ca/Alk अस्थिरता का कारण बन सकता है', ionicOk: 'Ca/Alk/Mg संतुलन ठीक' },
};
