export default {
  tabs: { dashboard: 'Dashboard', log: 'Registreren', trends: 'Trends', settings: 'Instellingen' },
  params: { temperature: 'Temperatuur', salinity: 'Saliniteit', ph: 'pH', alkalinity: 'Alkaliniteit', calcium: 'Calcium', magnesium: 'Magnesium', nitrate: 'Nitraat', phosphate: 'Fosfaat' },
  dashboard: { waterChemistry: 'Waterchemie', nutrients: 'Nutriënten', ratioNO3PO4: 'NO3:PO4 verhouding', ionicBalance: 'Ionisch evenwicht', noData: 'geen data' },
  log: { subtitle: 'Tik op een parameter om te registreren', cancel: 'Annuleren', save: 'Opslaan', saving: 'Opslaan...', step: 'Stap' },
  timers: { title: 'Salifert timers', shake: '30 sec schudden', wait: '3 min wachten', start: 'Start', cancel: 'Annuleren', done: 'Klaar' },
  trends: { consumptionRate: 'Verbruikssnelheid', consumptionHigh: 'Hoog verbruik — koralen groeien actief', consumptionNormal: 'Normaal — constante opname', consumptionStable: 'Stabiel — geen nettoverandering', consumptionRising: 'Stijgend — dosering controleren', history: 'Geschiedenis', noReadings: 'Geen metingen in deze periode', deleteTitle: 'Meting verwijderen', deleteMessage: '%{value} %{unit} van %{date}?', deleteConfirm: 'Verwijderen' },
  chart: { noReadings: 'Geen metingen', noReadingsHint: 'Registreer je eerste %{param} meting om trends te zien', current: 'Huidig', min: 'Min', max: 'Max', avg: 'Gem' },
  settings: { thresholds: 'Alarmdrempels', data: 'Gegevens', dosingLog: 'Doseringslog', exportCsv: 'Exporteer als CSV', noDataExport: 'Geen data', noDataExportMsg: 'Geen metingen om te exporteren.', save: 'Opslaan', warnLow: 'Warn laag', warnHigh: 'Warn hoog', critLow: 'Krit laag', critHigh: 'Krit hoog' },
  dosing: { title: 'Doseringslog', add: 'Dosis toevoegen', empty: 'Geen doseringen geregistreerd', emptyHint: 'Registreer je doseringen om ze te correleren met parameterwijzigingen', product: 'Product', productPlaceholder: 'Of typ productnaam...', amount: 'Hoeveelheid', notes: 'Notities', notesPlaceholder: 'Optioneel...', cancel: 'Annuleren', save: 'Opslaan', products: { kalkwasser: 'Kalkwasser', allForReef: 'All-for-Reef', caBalling: 'Ca (balling)', alkBalling: 'Alk (balling)', mgSupplement: 'Mg-supplement', aminoAcids: 'Aminozuren', coralFood: 'Koraalvoer' } },
  ratios: { po4Undetectable: 'PO4 niet detecteerbaar met verhoogd NO3 — risico op cyano/dino', no3Undetectable: 'NO3 niet detecteerbaar met verhoogd PO4 — nutriëntenonbalans', insufficientData: 'Onvoldoende gegevens', ratioLow: 'NO3:PO4 verhouding laag (%{ratio}:1) — fosfaatoverschot', ratioHigh: 'NO3:PO4 verhouding hoog (%{ratio}:1) — nitraatoverschot', ratioOk: 'NO3:PO4 verhouding %{ratio}:1', mgLow: 'Mg te laag t.o.v. Ca — eerst Mg verhogen', mgHigh: 'Mg te hoog t.o.v. Ca', mgInstability: 'Laag Mg kan Ca/Alk instabiliteit veroorzaken', ionicOk: 'Ca/Alk/Mg balans OK' },
};
