export default {
  tabs: { dashboard: 'Painel', log: 'Registar', trends: 'Tendências', dosing: 'Correções', settings: 'Definições' },
  params: { temperature: 'Temperatura', salinity: 'Salinidade', ph: 'pH', alkalinity: 'Alcalinidade', calcium: 'Cálcio', magnesium: 'Magnésio', nitrate: 'Nitratos', phosphate: 'Fosfatos', ammonia: 'Amónia', nitrite: 'Nitritos', potassium: 'Potássio', strontium: 'Estrôncio', iodine: 'Iodo', boron: 'Boro', silicate: 'Silicatos' },
  dashboard: { waterChemistry: 'Química da água', nutrients: 'Nutrientes', ratioNO3PO4: 'Rácio NO3:PO4', ionicBalance: 'Equilíbrio iónico', noData: 'sem dados' },
  log: { subtitle: 'Toque num parâmetro para registar', cancel: 'Cancelar', save: 'Guardar', saving: 'A guardar...', step: 'Passo' },
  timers: { title: 'Temporizadores Salifert', shake: 'Agitar 30 seg', wait: 'Esperar 3 min', start: 'Iniciar', cancel: 'Cancelar', done: 'Concluído' },
  trends: { consumptionRate: 'Taxa de consumo', consumptionHigh: 'Consumo alto — corais a crescer ativamente', consumptionNormal: 'Normal — absorção constante', consumptionStable: 'Estável — sem variação líquida', consumptionRising: 'A subir — verificar dosagem', history: 'Histórico', noReadings: 'Sem leituras neste período', deleteTitle: 'Eliminar leitura', deleteMessage: '%{value} %{unit} de %{date}?', deleteConfirm: 'Eliminar' },
  chart: { noReadings: 'Sem leituras', noReadingsHint: 'Registe a primeira leitura de %{param} para ver tendências', current: 'Atual', min: 'Mín', max: 'Máx', avg: 'Méd' },
  settings: { parameters: 'Parâmetros', thresholds: 'Limites de alerta', data: 'Dados', dosingLog: 'Registo de doses', exportCsv: 'Exportar como CSV', noDataExport: 'Sem dados', noDataExportMsg: 'Sem leituras para exportar.', save: 'Guardar', importCsv: 'Importar cópia de segurança CSV', importSuccess: 'Importação concluída', importSuccessMsg: '%{count} leituras importadas.', importError: 'Erro na importação', warnLow: 'Alerta baixo', warnHigh: 'Alerta alto', critLow: 'Crít baixo', critHigh: 'Crít alto' },
  dosing: { title: 'Registo de doses', add: 'Adicionar dose', empty: 'Sem doses registadas', emptyHint: 'Registe as suas doses para correlacionar com alterações de parâmetros', product: 'Produto', productPlaceholder: 'Ou escreva o nome do produto...', amount: 'Quantidade', notes: 'Notas', notesPlaceholder: 'Opcional...', cancel: 'Cancelar', save: 'Guardar', products: { kalkwasser: 'Kalkwasser', allForReef: 'All-for-Reef', caBalling: 'Ca (balling)', alkBalling: 'Alk (balling)', mgSupplement: 'Suplemento Mg', aminoAcids: 'Aminoácidos', coralFood: 'Alimento coral' } },
  ratios: { po4Undetectable: 'PO4 indetetável com NO3 elevado — risco de ciano/dinos', no3Undetectable: 'NO3 indetetável com PO4 elevado — desequilíbrio de nutrientes', insufficientData: 'Dados insuficientes', ratioLow: 'Rácio NO3:PO4 baixo (%{ratio}:1) — excesso de fosfatos', ratioHigh: 'Rácio NO3:PO4 alto (%{ratio}:1) — excesso de nitratos', ratioOk: 'Rácio NO3:PO4 %{ratio}:1', mgLow: 'Mg demasiado baixo em relação ao Ca — aumentar Mg primeiro', mgHigh: 'Mg demasiado alto em relação ao Ca', mgInstability: 'Mg baixo pode causar instabilidade Ca/Alk', ionicOk: 'Equilíbrio Ca/Alk/Mg OK' },
};
